version: "3.8"

services:
  taskoo-web:
    build: ./infrastructure/docker/
    container_name: taskoo.web
    tty: true
    ports:
      - 3000:3000
    command: >
      bash -c "./scripts/run.sh"
    volumes:
      - .:/opt/app/src
